### ISSUE TITLE
Missing Explorer Files

### ISSUE THREAD

**Issue by timperrett** [szeiger/extradoc#4]
Just noticed that in JsonMultiFactory.scala not all the JavaScript resources required are specified in the source code. Needed to add the following to stop errors in the browser when it went looking for javascript files that did not exist. 

```
  copyResource(p, "js/cache.js")
  copyResource(p, "js/diagrams.js")
  copyResource(p, "js/jit.js")
```

Adding these fixed it right up :-)

Cheers, Tim

**Comment by szeiger** [comment]
Thanks, added to master.
